name: Setup fasm
author: stevenwdv
description: Set up the flat assembler compiler

inputs:
  edition:
    description: Edition to install; fasm1, fasmg, or fasmarm
    required: false
    default: fasm1
  version:
    description: Version of edition to install; e.g. 1.73.30, 1.73.*, or latest
    required: false
    default: latest
  download-unknown:
    description: Try to download unknown versions; one of never, secure, a BLAKE2b-512 hash, or insecure
    required: false
    default: never
  custom-version-list:
    description: Specify a path to a local versions list file to use instead of stevenwdv/fasm-versions
    required: false
  assume-dynamic-unchanged:
    description: Assume dynamic versions (FASMARM) do not change compared to the cache; true or false
    required: false
    default: 'false'
  fasmg-download-packages:
    description: Download fasm g packages from tgrysztar/fasmg/packages; one of false, true, or some branch or commit or tags/<tag>
    required: false
    default: 'false'
  set-include-envvar:
    description: >-
      Set INCLUDE environment variable to the include folder(s) of the fasm installation, if found
      (for fasm g with input fasmg-download-packages on, this is the packages folder; also see fasmg-include-packages); true or false
    required: false
    default: 'true'
  fasmg-include-packages:
    description: >-
      Add specific packages (or the include folder inside them) to the INCLUDE environment variable,
      requires fasmg-download-packages input to be on, but not necessarily set-include-envvar; comma-separated list of package names
    required: false
    default: ''

outputs:
  path:
    description: Path to which binaries are installed (skipping any single root folder in the archive)
  edition:
    description: Installed edition, same as input
  version:
    description: Full installed version
  platform:
    description: Platform for which fasm was installed
  fasmg-packages:
    description: Path to fasm g packages directory, if downloaded; see fasmg-download-packages input

runs:
  using: node16
  main: dist/setup.js

branding:
  icon: cpu
  color: blue
